### ISSUE TITLE
Request: add hook for terragrunt formatting

### ISSUE THREAD

**Issue by aachkar-miovision** [gruntwork-io/pre-commit#22]
I am looking to include some terragrunt formatting checks both for local commits and as part of ci verification.

**Comment by yorinasub17** [comment]
Funny you ask because I was working on this! My WIP is here https://github.com/gruntwork-io/pre-commit/tree/yori-terragrunthclfmt

However, in testing I ran into a few issues caused by unsupported features in `hclfmt`. The two relevant issues that need to be fixed first are:

- https://github.com/gruntwork-io/terragrunt/issues/1091
- https://github.com/gruntwork-io/terragrunt/issues/1092

**Comment by yorinasub17** [comment]
This is now available in https://github.com/gruntwork-io/pre-commit/releases/tag/v0.1.4. Note that you will need terragrunt >=v0.23.3
